import math

#game settings
RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = math.floor(WIDTH * 0.5)
HALF_HEIGHT = math.floor(HEIGHT * 0.5)
FPS = 0

PLAYER_POS = 1.5, 5 # MINIMAP
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 100

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

#ray casting
FOV = math.pi /3
HALF_FOV =FOV/2
NUM_RAYS = math.floor(WIDTH * 0.5)
HALF_NUM_RAYS = math.floor(NUM_RAYS * 0.5)
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = math.floor(TEXTURE_SIZE * 0.5)